name: riverbloc_example
description: A simple example project to evaluate Riverpod with Cubits.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^0.12.1
  flutter_bloc: ^6.0.6
  riverbloc: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter
  
dependency_overrides:
  riverpod: any

flutter:
  uses-material-design: true
